# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.5.0
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.podman.annotations.ulimit: nofile=524288:524288,nproc=127181:127181
  creationTimestamp: "2023-05-22T15:14:01Z"
  labels:
    app: httpd-pod
  name: httpd-pod
spec:
  containers:
  - args:
    - /usr/bin/run-httpd
    image: quay.io/centos7/httpd-24-centos7:latest
    name: httpd
    ports:
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 8443
      hostPort: 8443
    securityContext:
      runAsNonRoot: true
    tty: true
